SELECT STUDENT.First_Name, STUDENT.Last_Name 
FROM STUDENT;

SELECT Distinct STUDENT.Major
FROM STUDENT;

SELECT STUDENT.First_Name, STUDENT.Last_Name 
FROM STUDENT
WHERE ZIP = 32828;


SELECT STUDENT.First_Name, STUDENT.Last_Name 
FROM STUDENT
WHERE ZIP = '97912' AND MAJOR = 'CS';


SELECT STUDENT.First_Name, STUDENT.Last_Name 
FROM STUDENT
WHERE MAJOR = '32826' OR '33186';


SELECT STUDENT.First_Name, STUDENT.Last_Name 
FROM STUDENT
WHERE MAJOR IN ('BUSINESS', 'MATHEMATICS');


SELECT STUDENT.First_Name, STUDENT.Last_Name 
FROM STUDENT
WHERE CLASS BETWEEN 2 AND 4;


SELECT STUDENT.First_Name, STUDENT.Last_Name 
FROM STUDENT
WHERE Last_Name LIKE 'M%';


SELECT STUDENT.First_Name, STUDENT.Last_Name 
FROM STUDENT
WHERE First_Name LIKE '_o%';


SELECT STUDENT.STATUS, COUNT(STATUS) AS CountStatus
FROM STUDENT
GROUP BY STATUS
ORDER BY COUNT(STATUS) ASC; 


